### ISSUE TITLE
Can't detect SY-300

### ISSUE THREAD

**Issue by mapper14** [ElliotGarbus/SY300Panel#2]
Got a new SY-300 turned on and connected to Win 7 SP1. Running SY-300 OS ver 1.03
Boss Tone Studio detects SY-300 and connects OK
Did install of SY300 as instructed.
SY300Panel consistently tells me my SY-300 Not Connected.
Not running touch
Any diagnostics or hints/incompatibilities to look for?

**Comment by ElliotGarbus** [comment]
Let me check on a few things, and I’ll have a response later today.

From: mapper14
Sent: Thursday, February 28, 2019 11:52 PM
To: ElliotGarbus/SY300Panel
Cc: Subscribed
Subject: [ElliotGarbus/SY300Panel] Can't detect SY-300 (#2)

Got a new SY-300 turned on and connected to Win 7 SP1. Running SY-300 OS ver 1.03
Boss Tone Studio detects SY-300 and connects OK
Did install of SY300 as instructed.
SY300Panel consistently tells me my SY-300 Not Connected.
Not running touch
Any diagnostics or hints/incompatibilities to look for?

**Comment by ElliotGarbus** [comment]
Here are a few ideas:

Make sure you are connected to the USB port of the SY300, not a USB to 
MIDI-DIN adapter.
Make sure the device ID is set to 17, this is the default value. To 
check it, on the SY300 press MENU, select SYSTEM, select MIDI, and set 
the device ID to 17.

Use a USB 2.0 port (not a USB3.0 port), I have seen issues with the 
SY300 with USB 3.0
Make sure the SY300 is on and connected prior to starting the SY300Panel

If these do not address your problem, there should be a log file 
directory located in a hidden directory, '.kivy'.  I will be under, 
C:\Users\your username\.kivy\logs Send me the most recent log file.  The 
log files have names like kivy_19-03-01.txt

The content of the file will look something like this:

[INFO   ] Logger: Record log in C:\Users\Elliot and 
Sharon\.kivy\logs\kivy_19-03-01_2.txt
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC 
v.1915 32 bit (Intel)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif 
(img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.5.13399 Compatibility Profile Context 
15.200.1062.1004'>
[INFO   ] GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] GL: OpenGL renderer <b'AMD Radeon HD 5800 Series'>
[INFO   ] GL: OpenGL parsed version: 4, 5
[INFO   ] GL: Shading version <b'4.40'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <18>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...

**Comment by mapper14** [comment]
Thanks so much Elliot,

-for the diagnostic details, I’ll try all that and give you a note back on success or fail.

I hope I can get it connected to your panel as it looks very very useful for my needs!

-Mike

**Comment by mapper14** [comment]
Elliot, Solved!

I am definitely connecting directly to the USB ‘B’ female port on the SY-300 and the  SY-300 is set to MIDI ID 17.

 

It turns out to be either my USB cable length, varying cable ‘quality’ or a misbehaving USB port on my Lenovo Thinkpad T420.

The one I was testing on is 3M length of unknown (or at least non-marked Asian) brand.  It passes signal for both data and audio from my GR-55 with no problems.

 

When I swapped for a 2M (not branded but heaver vinyl covering also of Asian origin) SY300Panel woke up just fine and responds perfectly to reflect patch and parameter changes on the unit.

The next step was swapping out another unbranded thinner cable also 3M length and it too also worked so that seems to rule out length alone.

I definitely know that a 4M USB cable will NOT pass signals reliably with my VG-99 and GR-55 but interestingly passes digital audio from my Mackie mixer just fine. I went through testing several 4M lengths from my local supplier doing a real time verification.

 

Then finally the last test that throws me back into suspecting that it really the Thinkpad port(s) (and/or how Windows 7 drivers are interfacing with them) is that I went back to the same cable that originally didn’t work and plugged into one of the other USB ports, and voila it works.

 

I’ve had these same USB  anomalies on different machines (all PCs) where one port seems dead one minute and alive later on.  Sometimes depending on which side of the chassis the USB is terminated on.

 

For the Thinkpad I’ll just have to mark the ‘good’ cables and ‘good’ and done with it.

 

BTW you are ElliotG on VGuitar Forum right?  If correct, many kudos for your ambient patches. These type of sounds are what I’m seeking as I mostly try to stylize my guitar work with a big nod to many of the Euro/Brit ambient/chill-out stylists always with an eye towards potential film scoring:  artists like Carbon Based Lifeforms, Sounds From The Ground, Beanfield, Boards of Canada, Chris Zippel, Bonobo, and because I recently picked up the cello, the amazing looping work of Zoe Keating.  Can’t wait to send a cello pickup through the SY-300.  Still trying to settle on a cello pickup that doesn’t break the wallet so I’m mic’ing it right now.

 

Before getting this SY-300 I have been chaining my GR-55 through USB into the Thinkpad to trigger and blend it’s output with some Native Instrument softsynths such as Massive.  That can often produce some very nice sonic  enhancements to simpler straight-up GR patches, so naturally I want to start chaining the GR-55 guitar out into the SY-300.

  

I also try my hand at acoustic and electric bass and so am looking forward to exploring that instrument through the SY-300.

 

I hardly every play old school rock so I don’t have much interest in shredder/metal/screamer guitar styles. 

 

Thanks again Elliot for your attention and care, its eally appreciated!

 

Jazzy Cheers,

Mike,  -in Vancouver BC Canada

**Comment by ElliotGarbus** [comment]
Mike, Glad to hear it was an easy fix. I hope you like the SY300Panel. Let me know what you think. 

Thanks for the compliment, yes, I’m ElliotG on VGuitarforums. 

-Elliot

**Comment by ElliotGarbus** [comment]
Mike,

You said, ‘I’ve had these same USB anomalies on different machines … Sometimes depending on which side of the chassis the USB is terminated on.’
Here is some extra info that may help in the future:  Take a look at the color of the plastic tab inside the USB ports of your laptop.  The black ports are USB 2.x and the Blue ports are USB 3.x.   As I mentioned earlier, the Boss SY300 does not seem to operate properly with a USB 2.x connection.  Make sure you are using the black USB ports on your laptop when connecting the SY300.

Elliot

**Comment by ElliotGarbus** [comment]
Issue was a bad usb cable.

**Comment by mapper14** [comment]
Thanks Elliot,

Good tip..didna’ know that they were colour coded.

-mike
