### ISSUE TITLE
Running on Linux - dependencies

### ISSUE THREAD

**Issue by godber** [ElliotGarbus/SY300Panel#3]
I was interested in looking at this package as a Kivy example, specifically to learn about cross platform packaging.  The package lacks a `setup.py` or `requirements.txt` so understanding what python packages are required to work with the source may be confusing to people.  I understand that this doesn't matter much if the end goal is to distribute binaries.

I'd be willing to help in these packaging areas ... cross platform even, I have access to Mac, Linux, Windows, iOS and Android platforms.

**Comment by godber** [comment]
The real point of me submitting this issue was to share the steps I took to get it running on Linux (I don't actually have a SY300, so by running, I just mean the GUI).  It was fairly straight forward:

```
sudo apt install libjack-dev
mkvirtualenv -p `which python3` sy300
pip install mido kivy python-rtmidi
python3 ./main.py 
```

Output of my `pip freeze`:

```
certifi==2019.3.9
chardet==3.0.4
docutils==0.14
idna==2.8
Kivy==1.10.1
Kivy-Garden==0.1.4
mido==1.2.9
pkg-resources==0.0.0
Pygments==2.3.1
python-rtmidi==1.2.1
requests==2.21.0
urllib3==1.24.1
```

**Comment by godber** [comment]
@ElliotGarbus You can just close this issue if you want.  I just kind of figured it might prove useful to someone who comes across your project.  Or we can talk about Python packages and isolated environments (virtualenv) if you want.

**Comment by ElliotGarbus** [comment]
Thanks Austin!

**Comment by godber** [comment]
One thing that has occurred to me is that I had already done some form of Kivy setup on the Ubuntu 18.04 system I tested this on.  I don't recall which method, but something from this URL I think:

https://kivy.org/doc/stable/installation/installation-linux.html

So that's why installing kivy in the virtualenv was as easy as it was above.  Users who have not gone through the system wide Kivy install will likely have to resolve some dependencies
