### ISSUE TITLE
moving patches on and off the SY-300

### ISSUE THREAD

**Issue by dtenenba** [ElliotGarbus/SY300Panel#4]
Hi,

This is not really an issue with your code, I just had a question. 

But first - the code looks great - I'm going to try to install it (I'm on a Mac).

I saw someone selling [SY-300 patches](https://empyreanfx.com/product/boss-sy-300-ultimate-patches/) and I don't understand how you can get patches on and off the SY-300. Even Boss Tone Studio does not provide a way. It says it's in "tsl format" - do you know what that is?

So basically I am just wondering if there is a way to 1) save patches from the SY-300 onto a computer so I can have backups and share them with others, and 2) load patches from a file onto the SY-300. 

I realize you might not know the answer, so no need to reply if you don't. 

I'm looking through the SY-300 MIDI implementation guide which I am sure you are quite familiar with. Looks like it is possible to grab all the information about a patch by just parsing the MIDI from the SY-300?

Thanks....

**Comment by ElliotGarbus** [comment]
I have not run this code on a mac.  While I don't expect it would take much effort for me to get it working, it would be non-trivial if you are not familiar with Python and Kivy.  If you are familiar with kivy I suspect it will need some changes made to accommodate the increased screen density on the Mac. 

Moving on the the SY300.  In the Boss Tone Studio, if you select Librarian on the editor librarian toggle in the upper left side of the editor, a menu bar will appear at the top that  includes import and export.  You create a liveset, drag patches to it and then export.  This will save all of the patches in the selected live set.  The patches are saved in a file with .tsl extension.  This is actually a JSON file, and contains the information of the patches.  

Do not buy the patches from the site you have attached.  Those patches are all available for free at: https://www.vguitarforums.com/smf/
The person selling those patches violated the user agreement at vguitar forums, scooped up all the patches and is selling them.

Enjoy!

**Comment by dtenenba** [comment]
Thanks. I actually got the code to run with very little fuss. Looks great!

Thanks for the tips on exporting/importing patches, and for the low-down on the patches I found.

**Comment by ElliotGarbus** [comment]
I'm delighted to hear you got the code up and running.  Enjoy!
